{% set name = "mkdocstrings-python-legacy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 36d160ac7af5a3cec764eeb66522f42a116088a41289e04372592b91e14abbbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - mkdocstrings >=0.19
    - python >={{ python_min }}
    - pytkdocs >=0.14
    - mkdocs-autorefs >=1.1

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/mkdocstrings-python-legacy/
  summary: A legacy Python handler for mkdocstrings.
  license: ISC
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/python-legacy
  dev_url: https://github.com/mkdocstrings/python-legacy

extra:
  recipe-maintainers:
    - bandersen23
